### PR TITLE
Edit

### PR DESCRIPTION
**Pull request by yungyung616**
I tried to modify some alignment in index and giving the editing function in member profile page. The editing function,however ,is not yet finished.

### CODE REVIEW

**Comment by scyan123** [comment]
I will edit the alignment of the table in the index.

**Comment by hkcm189** [comment]
The footer of layout also has to be changed in some pages, I'll try to handle it.

**Comment by hkkcliu** [comment]
When you are fixing the alignment part, you may think more about the flexibility problem. Although the mobile view page is not required, we need to consider the resolution of different monitors!!!!

**Comment by hkcm189** [comment]
any functions also need to add?

**Comment by hkkcliu** [comment]
Remember what Peter said, we don't need too many functions, but two to three deep and wide MAIN functions. And our coding should focus on the team forming part also!!!

**Comment by henryszex42s** [comment]
Yes , I agreed with you that, I think we should apply some of the function to suggest the teams which have the empty space in the related position.

**Pull request merged**
