### PR TITLE
new edition base on demo

### PR DESCRIPTION
**Pull request by hkcm189**
seems like the demo is much more easier to react with firebase and angular......so i edit the team, admin pages from the demo and add a new page called search member....please check..

### CODE REVIEW

**Comment by henryszex42s** [comment]
The navigation bar is not working in admin page,
and I think that is a bad idea to remove the library from the page, some of the function are broken.

**Comment by sclamac** [comment]
let me fix the navigation bar first
Then i send back the pull requests and continuous to do others.

**Comment by hkkcliu** [comment]
If you removed the library without checking, it might cause some conflicts to some functions which laid on them.

**Comment by hkcm189** [comment]
okok sorry about that, I moved back the library into the assets folder, please check if the conflicts are still happened...

**Comment by scyan123** [comment]
The navigation bar seems not working properly without the library

**Comment by hkkcliu** [comment]
And you should backup the files before the "BIG" changes.

**Comment by lamwyman** [comment]
It will be fixed later

**Comment by hkcm189** [comment]
okok sorry about that, I moved back the library into the assets folder, please check if the conflicts are still happened...

**Pull request merged**
